REVOKE ALL ON ALL TABLES IN SCHEMA public FROM {{APP_DB_ROLE}};
GRANT USAGE ON SCHEMA public TO {{APP_DB_ROLE}};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO {{APP_DB_ROLE}};
REVOKE ALL ON schema_migrations FROM {{APP_DB_ROLE}};
REVOKE UPDATE, DELETE ON audit_log FROM {{APP_DB_ROLE}};
